//
// File generated by rootcint at Fri Aug 25 08:28:44 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DQMviewerdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DQMviewerdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SDGUI_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_SDGUI(void *p);
   static void deleteArray_SDGUI(void *p);
   static void destruct_SDGUI(void *p);
   static void streamer_SDGUI(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SDGUI*)
   {
      ::SDGUI *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SDGUI >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SDGUI", ::SDGUI::Class_Version(), "./DQMviewer.h", 25,
                  typeid(::SDGUI), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SDGUI::Dictionary, isa_proxy, 0,
                  sizeof(::SDGUI) );
      instance.SetDelete(&delete_SDGUI);
      instance.SetDeleteArray(&deleteArray_SDGUI);
      instance.SetDestructor(&destruct_SDGUI);
      instance.SetStreamerFunc(&streamer_SDGUI);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SDGUI*)
   {
      return GenerateInitInstanceLocal((::SDGUI*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SDGUI*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SDGUI::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SDGUI::Class_Name()
{
   return "SDGUI";
}

//______________________________________________________________________________
const char *SDGUI::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SDGUI*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SDGUI::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SDGUI*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SDGUI::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SDGUI*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SDGUI::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SDGUI*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SDGUI::Streamer(TBuffer &R__b)
{
   // Stream an object of class SDGUI.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void SDGUI::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SDGUI.
      TClass *R__cl = ::SDGUI::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mainFrame", &mainFrame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tab", &tab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_frame", &sd_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_objtabs[100]", &sd_objtabs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_tab", &sd_tab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_frame", &fd_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_objtabs[100]", &fd_objtabs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_tab", &fd_tab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_frame", &hy_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_objtabs[100]", &hy_objtabs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_tab", &hy_tab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_frame", &rd_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_objtabs[100]", &rd_objtabs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_tab", &rd_tab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_frame", &md_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_objtabs[100]", &md_objtabs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_tab", &md_tab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_energy", &sd_energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_ref_frame", &sd_ref_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_dqm_frame", &sd_dqm_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_ref_period", &sd_ref_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_dqm_period", &sd_dqm_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_eyebox", &fd_eyebox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_ref_frame", &fd_ref_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_dqm_frame", &fd_dqm_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_ref_period", &fd_ref_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_dqm_period", &fd_dqm_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_eyebox", &hy_eyebox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_ref_frame", &hy_ref_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_dqm_frame", &hy_dqm_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_ref_period", &hy_ref_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_dqm_period", &hy_dqm_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_ref_frame", &rd_ref_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_dqm_frame", &rd_dqm_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_ref_period", &rd_ref_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_dqm_period", &rd_dqm_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_ref_frame", &md_ref_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_dqm_frame", &md_dqm_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_ref_period", &md_ref_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_dqm_period", &md_dqm_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sd_canvas[100]", &sd_canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fd_canvas[100]", &fd_canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hy_canvas[100]", &hy_canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rd_canvas[100]", &rd_canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*md_canvas[100]", &md_canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fileStatusBar", &fileStatusBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sdStatusBar", &sdStatusBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fdStatusBar", &fdStatusBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hyStatusBar", &hyStatusBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rdStatusBar", &rdStatusBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mdStatusBar", &mdStatusBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sel_objtabs", &sel_objtabs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sdEnergySelect", &sdEnergySelect);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fdEyeSelect", &fdEyeSelect);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hyEyeSelect", &hyEyeSelect);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hint_plots", &hint_plots);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hint_status", &hint_status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hint_period", &hint_period);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hint_seltab", &hint_seltab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hint", &hint);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_SDGUI(void *p) {
      delete ((::SDGUI*)p);
   }
   static void deleteArray_SDGUI(void *p) {
      delete [] ((::SDGUI*)p);
   }
   static void destruct_SDGUI(void *p) {
      typedef ::SDGUI current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_SDGUI(TBuffer &buf, void *obj) {
      ((::SDGUI*)obj)->::SDGUI::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::SDGUI

/********************************************************
* DQMviewerdict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDQMviewerdict();

extern "C" void G__set_cpp_environmentDQMviewerdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DQMviewer.h");
  G__cpp_reset_tagtableDQMviewerdict();
}
#include <new>
extern "C" int G__cpp_dllrevDQMviewerdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SDGUI */
static int G__DQMviewerdict_405_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SDGUI* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SDGUI(
(TGWindow*) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])
, (unsigned int) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) SDGUI(
(TGWindow*) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])
, (unsigned int) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->ClearList();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((SDGUI*) G__getstructoffset())->GetPeriod(*((string*) G__int(libp->para[0])));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->GetParsedStrings(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->GetGraphFromMultiGraph((TMultiGraph*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->FindMatchingDqmObject((TObject*) G__int(libp->para[0]), (TList*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->FindMatchingResidual((TH1*) G__int(libp->para[0]), (TList*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->FindMatchingConsistencyTest((TH2*) G__int(libp->para[0]), (TList*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->ApplyHistogramStyle((TH1*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->ApplyGraphStyle((TGraph*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->ApplyResidualStyle((TGraphErrors*) G__int(libp->para[0]), (TH1*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SDGUI*) G__getstructoffset())->ApplyMultiGraphStyle((TMultiGraph*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 75, (long) ((SDGUI*) G__getstructoffset())->DrawRecPlots(*((string*) G__int(libp->para[0])), (TRootEmbeddedCanvas**) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SDGUI*) G__getstructoffset())->DrawHistogram1D((TH1*) G__int(libp->para[0]), (TRootEmbeddedCanvas*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SDGUI*) G__getstructoffset())->DrawHistogram2D((TH2*) G__int(libp->para[0]), (TRootEmbeddedCanvas*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SDGUI*) G__getstructoffset())->DrawMultiGraph((TMultiGraph*) G__int(libp->para[0]), (TRootEmbeddedCanvas*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DisplayLDFMultiGraphStat((TGraph*) G__int(libp->para[0]), (TGraph*) G__int(libp->para[1])
, (TF1*) G__int(libp->para[2]), (TF1*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DisplayHistogramStat((TF1*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SDGUI*) G__getstructoffset())->GetLDFMultiGraphStatus((TF1*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SDGUI*) G__getstructoffset())->GetHistogramStatus((TF1*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->UpdateTabColorStatus((Pixel_t*) G__int(libp->para[0]), (TGTab*) G__int(libp->para[1])
, (TGCompositeFrame**) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->UpdateTab((int) G__int(libp->para[0]), (TRootEmbeddedCanvas**) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DoTab((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DoTabSD((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DoTabFD((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DoTabHY((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DoTabRD((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->DoTabMD((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->EyeSelect((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->EnergySelect((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SDGUI::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SDGUI::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SDGUI::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SDGUI::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SDGUI*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SDGUI::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SDGUI::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SDGUI::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DQMviewerdict_405_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SDGUI::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SDGUI G__TSDGUI;
static int G__DQMviewerdict_405_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SDGUI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SDGUI*) (soff+(sizeof(SDGUI)*i)))->~G__TSDGUI();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SDGUI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SDGUI*) (soff))->~G__TSDGUI();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SDGUI */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDQMviewerdict {
 public:
  G__Sizep2memfuncDQMviewerdict(): p(&G__Sizep2memfuncDQMviewerdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDQMviewerdict::*p)();
};

size_t G__get_sizep2memfuncDQMviewerdict()
{
  G__Sizep2memfuncDQMviewerdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDQMviewerdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI))) {
     SDGUI *G__Lderived;
     G__Lderived=(SDGUI*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI),G__get_linked_tagnum(&G__DQMviewerdictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDQMviewerdict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Pixel_t",107,-1,0,-1);
   G__setnewtype(-1,"Pixel value",0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__DQMviewerdictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SDGUI */
static void G__setup_memvarSDGUI(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI));
   { SDGUI *p; p=(SDGUI*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGHorizontalFrame),-1,-1,4,"mainFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGTab),-1,-1,4,"tab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"sd_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"sd_objtabs[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGTab),-1,-1,4,"sd_tab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"fd_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"fd_objtabs[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGTab),-1,-1,4,"fd_tab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"hy_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"hy_objtabs[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGTab),-1,-1,4,"hy_tab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"rd_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"rd_objtabs[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGTab),-1,-1,4,"rd_tab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"md_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"md_objtabs[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGTab),-1,-1,4,"md_tab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"sd_energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"sd_ref_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"sd_dqm_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"sd_ref_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"sd_dqm_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"fd_eyebox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"fd_ref_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"fd_dqm_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"fd_ref_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"fd_dqm_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"hy_eyebox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"hy_ref_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"hy_dqm_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"hy_ref_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"hy_dqm_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"rd_ref_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"rd_dqm_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"rd_ref_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"rd_dqm_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"md_ref_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"md_dqm_frame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"md_ref_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLabel),-1,-1,4,"md_dqm_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TRootEmbeddedCanvas),-1,-1,4,"sd_canvas[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TRootEmbeddedCanvas),-1,-1,4,"fd_canvas[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TRootEmbeddedCanvas),-1,-1,4,"hy_canvas[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TRootEmbeddedCanvas),-1,-1,4,"rd_canvas[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TRootEmbeddedCanvas),-1,-1,4,"md_canvas[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGStatusBar),-1,-1,4,"fileStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGStatusBar),-1,-1,4,"sdStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGStatusBar),-1,-1,4,"fdStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGStatusBar),-1,-1,4,"hyStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGStatusBar),-1,-1,4,"rdStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGStatusBar),-1,-1,4,"mdStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGCompositeFrame),-1,-1,4,"sel_objtabs=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGComboBox),-1,-1,4,"sdEnergySelect=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGComboBox),-1,-1,4,"fdEyeSelect=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGComboBox),-1,-1,4,"hyEyeSelect=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLayoutHints),-1,-1,4,"hint_plots=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLayoutHints),-1,-1,4,"hint_status=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLayoutHints),-1,-1,4,"hint_period=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLayoutHints),-1,-1,4,"hint_seltab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TGLayoutHints),-1,-1,4,"hint=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DQMviewerdictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDQMviewerdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSDGUI(void) {
   /* SDGUI */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI));
   G__memfunc_setup("SDGUI",380,G__DQMviewerdict_405_0_1, 105, G__get_linked_tagnum(&G__DQMviewerdictLN_SDGUI), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - - 0 - w "
"h - - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearList",899,G__DQMviewerdict_405_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeriod",899,G__DQMviewerdict_405_0_3, 117, G__get_linked_tagnum(&G__DQMviewerdictLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParsedStrings",1641,G__DQMviewerdict_405_0_4, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - str", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGraphFromMultiGraph",2211,G__DQMviewerdict_405_0_5, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TGraph), -1, 0, 2, 1, 1, 0, 
"U 'TMultiGraph' - 0 - mg u 'string' - 0 - header", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindMatchingDqmObject",2085,G__DQMviewerdict_405_0_6, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TObject), -1, 0, 2, 1, 1, 0, 
"U 'TObject' - 0 - ref U 'TList' - 0 - list", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindMatchingResidual",2021,G__DQMviewerdict_405_0_7, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TGraphErrors), -1, 0, 2, 1, 1, 0, 
"U 'TH1' - 0 - ref U 'TList' - 0 - list", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindMatchingConsistencyTest",2782,G__DQMviewerdict_405_0_8, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TH1), -1, 0, 2, 1, 1, 0, 
"U 'TH2' - 0 - ref U 'TList' - 0 - list", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ApplyHistogramStyle",1989,G__DQMviewerdict_405_0_9, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TH1), -1, 0, 1, 1, 1, 0, "U 'TH1' - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ApplyGraphStyle",1545,G__DQMviewerdict_405_0_10, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TGraph), -1, 0, 2, 1, 1, 0, 
"U 'TGraph' - 0 - g u 'string' - 0 - header", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ApplyResidualStyle",1872,G__DQMviewerdict_405_0_11, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TGraphErrors), -1, 0, 2, 1, 1, 0, 
"U 'TGraphErrors' - 0 - ge U 'TH1' - 0 - histo1d_ref", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ApplyMultiGraphStyle",2068,G__DQMviewerdict_405_0_12, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TMultiGraph), -1, 0, 1, 1, 1, 0, "U 'TMultiGraph' - 0 - mg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawRecPlots",1210,G__DQMviewerdict_405_0_13, 75, -1, G__defined_typename("Pixel_t"), 0, 2, 1, 1, 0, 
"u 'string' - 0 - selected_stream U 'TRootEmbeddedCanvas' - 2 - canvas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawHistogram1D",1457,G__DQMviewerdict_405_0_14, 107, -1, G__defined_typename("Pixel_t"), 0, 2, 1, 1, 0, 
"U 'TH1' - 0 - histo1d_ref U 'TRootEmbeddedCanvas' - 0 - canvas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawHistogram2D",1458,G__DQMviewerdict_405_0_15, 107, -1, G__defined_typename("Pixel_t"), 0, 2, 1, 1, 0, 
"U 'TH2' - 0 - histo2d_ref U 'TRootEmbeddedCanvas' - 0 - canvas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawMultiGraph",1419,G__DQMviewerdict_405_0_16, 107, -1, G__defined_typename("Pixel_t"), 0, 2, 1, 1, 0, 
"U 'TMultiGraph' - 0 - mg U 'TRootEmbeddedCanvas' - 0 - canvas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayLDFMultiGraphStat",2373,G__DQMviewerdict_405_0_17, 121, -1, -1, 0, 4, 1, 1, 0, 
"U 'TGraph' - 0 - gREF U 'TGraph' - 0 - gDQM "
"U 'TF1' - 0 - fREF U 'TF1' - 0 - fDQM", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayHistogramStat",2080,G__DQMviewerdict_405_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TF1' - 0 - func", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLDFMultiGraphStatus",2167,G__DQMviewerdict_405_0_19, 107, -1, G__defined_typename("Pixel_t"), 0, 3, 1, 1, 0, 
"U 'TF1' - 0 - f d - - 0 - min "
"d - - 0 - max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistogramStatus",1874,G__DQMviewerdict_405_0_20, 107, -1, G__defined_typename("Pixel_t"), 0, 1, 1, 1, 0, "U 'TF1' - 0 - func", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTabColorStatus",2045,G__DQMviewerdict_405_0_21, 121, -1, -1, 0, 3, 1, 1, 0, 
"K - 'Pixel_t' 0 - status U 'TGTab' - 0 - tab "
"U 'TGCompositeFrame' - 2 - htab", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTab",890,G__DQMviewerdict_405_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - id U 'TRootEmbeddedCanvas' - 2 - canvas", "not working yet", (void*) NULL, 0);
   G__memfunc_setup("DoTab",458,G__DQMviewerdict_405_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTabSD",609,G__DQMviewerdict_405_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTabFD",596,G__DQMviewerdict_405_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTabHY",619,G__DQMviewerdict_405_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTabRD",608,G__DQMviewerdict_405_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTabMD",603,G__DQMviewerdict_405_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EyeSelect",899,G__DQMviewerdict_405_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnergySelect",1226,G__DQMviewerdict_405_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DQMviewerdict_405_0_31, 85, G__get_linked_tagnum(&G__DQMviewerdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SDGUI::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DQMviewerdict_405_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SDGUI::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DQMviewerdict_405_0_33, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SDGUI::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DQMviewerdict_405_0_34, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SDGUI::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DQMviewerdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DQMviewerdict_405_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DQMviewerdict_405_0_39, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SDGUI::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DQMviewerdict_405_0_40, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SDGUI::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DQMviewerdict_405_0_41, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SDGUI::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DQMviewerdict_405_0_42, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SDGUI::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~SDGUI", 506, G__DQMviewerdict_405_0_43, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDQMviewerdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDQMviewerdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDQMviewerdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DQMviewerdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TH2 = { "TH2" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TGraphErrors = { "TGraphErrors" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_TMultiGraph = { "TMultiGraph" , 99 , -1 };
G__linked_taginfo G__DQMviewerdictLN_SDGUI = { "SDGUI" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDQMviewerdict() {
  G__DQMviewerdictLN_TClass.tagnum = -1 ;
  G__DQMviewerdictLN_TBuffer.tagnum = -1 ;
  G__DQMviewerdictLN_TMemberInspector.tagnum = -1 ;
  G__DQMviewerdictLN_TObject.tagnum = -1 ;
  G__DQMviewerdictLN_string.tagnum = -1 ;
  G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DQMviewerdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DQMviewerdictLN_TList.tagnum = -1 ;
  G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DQMviewerdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DQMviewerdictLN_TGObject.tagnum = -1 ;
  G__DQMviewerdictLN_TQObject.tagnum = -1 ;
  G__DQMviewerdictLN_TGWindow.tagnum = -1 ;
  G__DQMviewerdictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__DQMviewerdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DQMviewerdictLN_TGFrame.tagnum = -1 ;
  G__DQMviewerdictLN_TGCompositeFrame.tagnum = -1 ;
  G__DQMviewerdictLN_TGLayoutHints.tagnum = -1 ;
  G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DQMviewerdictLN_TGHorizontalFrame.tagnum = -1 ;
  G__DQMviewerdictLN_TGMainFrame.tagnum = -1 ;
  G__DQMviewerdictLN_TGTab.tagnum = -1 ;
  G__DQMviewerdictLN_TGLabel.tagnum = -1 ;
  G__DQMviewerdictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__DQMviewerdictLN_TGStatusBar.tagnum = -1 ;
  G__DQMviewerdictLN_TGComboBox.tagnum = -1 ;
  G__DQMviewerdictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DQMviewerdictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DQMviewerdictLN_TF1.tagnum = -1 ;
  G__DQMviewerdictLN_TH1.tagnum = -1 ;
  G__DQMviewerdictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__DQMviewerdictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__DQMviewerdictLN_TH2.tagnum = -1 ;
  G__DQMviewerdictLN_TGraph.tagnum = -1 ;
  G__DQMviewerdictLN_TGraphErrors.tagnum = -1 ;
  G__DQMviewerdictLN_TMultiGraph.tagnum = -1 ;
  G__DQMviewerdictLN_SDGUI.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDQMviewerdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_string);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TList);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGLayoutHints);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TF1);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TH1);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TH2);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TGraphErrors);
   G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_TMultiGraph);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DQMviewerdictLN_SDGUI),sizeof(SDGUI),-1,62464,(char*)NULL,G__setup_memvarSDGUI,G__setup_memfuncSDGUI);
}
extern "C" void G__cpp_setupDQMviewerdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupDQMviewerdict()");
  G__set_cpp_environmentDQMviewerdict();
  G__cpp_setup_tagtableDQMviewerdict();

  G__cpp_setup_inheritanceDQMviewerdict();

  G__cpp_setup_typetableDQMviewerdict();

  G__cpp_setup_memvarDQMviewerdict();

  G__cpp_setup_memfuncDQMviewerdict();
  G__cpp_setup_globalDQMviewerdict();
  G__cpp_setup_funcDQMviewerdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDQMviewerdict();
  return;
}
class G__cpp_setup_initDQMviewerdict {
  public:
    G__cpp_setup_initDQMviewerdict() { G__add_setup_func("DQMviewerdict",(G__incsetup)(&G__cpp_setupDQMviewerdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDQMviewerdict() { G__remove_setup_func("DQMviewerdict"); }
};
G__cpp_setup_initDQMviewerdict G__cpp_setup_initializerDQMviewerdict;

