/********************************************************************
* DQMviewerdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DQMviewerdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDQMviewerdict();
extern void G__cpp_setup_inheritanceDQMviewerdict();
extern void G__cpp_setup_typetableDQMviewerdict();
extern void G__cpp_setup_memvarDQMviewerdict();
extern void G__cpp_setup_globalDQMviewerdict();
extern void G__cpp_setup_memfuncDQMviewerdict();
extern void G__cpp_setup_funcDQMviewerdict();
extern void G__set_cpp_environmentDQMviewerdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DQMviewer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DQMviewerdictLN_TClass;
extern G__linked_taginfo G__DQMviewerdictLN_TBuffer;
extern G__linked_taginfo G__DQMviewerdictLN_TMemberInspector;
extern G__linked_taginfo G__DQMviewerdictLN_TObject;
extern G__linked_taginfo G__DQMviewerdictLN_string;
extern G__linked_taginfo G__DQMviewerdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DQMviewerdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DQMviewerdictLN_TList;
extern G__linked_taginfo G__DQMviewerdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DQMviewerdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DQMviewerdictLN_TGObject;
extern G__linked_taginfo G__DQMviewerdictLN_TQObject;
extern G__linked_taginfo G__DQMviewerdictLN_TGWindow;
extern G__linked_taginfo G__DQMviewerdictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__DQMviewerdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__DQMviewerdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DQMviewerdictLN_TGFrame;
extern G__linked_taginfo G__DQMviewerdictLN_TGCompositeFrame;
extern G__linked_taginfo G__DQMviewerdictLN_TGLayoutHints;
extern G__linked_taginfo G__DQMviewerdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DQMviewerdictLN_TGHorizontalFrame;
extern G__linked_taginfo G__DQMviewerdictLN_TGMainFrame;
extern G__linked_taginfo G__DQMviewerdictLN_TGTab;
extern G__linked_taginfo G__DQMviewerdictLN_TGLabel;
extern G__linked_taginfo G__DQMviewerdictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__DQMviewerdictLN_TGStatusBar;
extern G__linked_taginfo G__DQMviewerdictLN_TGComboBox;
extern G__linked_taginfo G__DQMviewerdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DQMviewerdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DQMviewerdictLN_TF1;
extern G__linked_taginfo G__DQMviewerdictLN_TH1;
extern G__linked_taginfo G__DQMviewerdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DQMviewerdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DQMviewerdictLN_TH2;
extern G__linked_taginfo G__DQMviewerdictLN_TGraph;
extern G__linked_taginfo G__DQMviewerdictLN_TGraphErrors;
extern G__linked_taginfo G__DQMviewerdictLN_TMultiGraph;
extern G__linked_taginfo G__DQMviewerdictLN_SDGUI;

/* STUB derived class for protected member access */
